### ISSUE TITLE
Installation error - error C2660: 'v8::Value::BooleanValue': function does not take 0 arguments

### ISSUE THREAD

**Issue by p-g-krish** [jimfilippou/mitsobox#5]
C:\Dev\Test\exe>npm i mitsobox

> ref@1.3.5 install C:\Dev\Test\node_modules\ref
> node-gyp rebuild

C:\Dev\Test\node_modules\ref>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )
  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  binding.cc
  win_delay_load_hook.cc
C:\Dev\Test\node_modules\ref\src\binding.cc(222): error C2660: 'v8::Value::BooleanValue': function does not take 0 arguments [C:\Dev\Test\node_modules\ref\build\binding.vcxproj]
  c:\users\devU\.node-gyp\13.10.1\include\node\v8.h(2771): note: see declaration of 'v8::Value::BooleanValue' (compiling source file ..\src\binding.cc)
C:\Dev\Test\node_modules\ref\src\binding.cc(253): error C2660: 'v8::Value::Uint32Value': function does not take 0 arguments [C:\Dev\Test\node_modules\ref\build\binding.vcxproj]
  c:\users\devU\.node-gyp\13.10.1\include\node\v8.h(2776): note: see declaration of 'v8::Value::Uint32Value' (compiling source file ..\src\binding.cc)
C:\Dev\Test\node_modules\ref\src\binding.cc(360): error C2664: 'v8::String::Utf8Value::Utf8Value(const v8::String::Utf8Value &)': cannot convert argument 1 from 'v8::Local<v8::Value>'
 to 'const v8::String::Utf8Value &'
 [C:\Dev\Test\node_modules\ref\build\binding.vcxproj]
  C:\Dev\Test\node_modules\ref\src\binding.cc(360): note: Reason: cannot convert from 'v8::Local<v8::Value>' to 'const v8::String::Utf8Value'
  C:\Dev\Test\node_modules\ref\src\binding.cc(360): note: No user-defined-conversion operator available that can perform this conversion, or the operator cannot be called
C:\Dev\Test\node_modules\ref\src\binding.cc(447): error C2664: 'v8::String::Utf8Value::Utf8Value(const v8::String::Utf8Value &)': cannot convert argument 1 from 'v8::Local<v8::Value>'
 to 'const v8::String::Utf8Value &' 
[C:\Dev\Test\node_modules\ref\build\binding.vcxproj]
  C:\Dev\Test\node_modules\ref\src\binding.cc(447): note: Reason: cannot convert from 'v8::Local<v8::Value>' to 'const v8::String::Utf8Value'
  C:\Dev\Test\node_modules\ref\src\binding.cc(447): note: No user-defined-conversion operator available that can perform this conversion, or the operator cannot be called
C:\Dev\Test\node_modules\ref\src\binding.cc(521): error C2660: 'v8::Value::Uint32Value': function does not take 0 arguments [C:\Dev\Test\node_modules\ref\build\binding.vcxproj]
  c:\users\devU\.node-gyp\13.10.1\include\node\v8.h(2776): note: see declaration of 'v8::Value::Uint32Value' (compiling source file ..\src\binding.cc)
C:\Dev\Test\node_modules\ref\src\binding.cc(550): error C2660: 'v8::Value::Uint32Value': function does not take 0 arguments [C:\Dev\Test\node_modules\ref\build\binding.vcxproj]
  c:\users\devU\.node-gyp\13.10.1\include\node\v8.h(2776): note: see declaration of 'v8::Value::Uint32Value' (compiling source file ..\src\binding.cc)
C:\Dev\Test\node_modules\ref\src\binding.cc(582): error C2661: 'v8::Object::Set': no overloaded function takes 2 arguments [C:\Dev\Test\node_modules\ref\build\binding.vcxproj]
C:\Dev\Test\node_modules\ref\src\binding.cc(583): error C2661: 'v8::Object::Set': no overloaded function takes 2 arguments [C:\Dev\Test\node_modules\ref\build\binding.vcxproj]
C:\Dev\Test\node_modules\ref\src\binding.cc(584): error C2661: 'v8::Object::Set': no overloaded function takes 2 arguments [C:\Dev\Test\node_modules\ref\build\binding.vcxproj]
C:\Dev\Test\node_modules\ref\src\binding.cc(585): error C2661: 'v8::Object::Set': no overloaded function takes 2 arguments [C:\Dev\Test\node_modules\ref\build\binding.vcxproj]
C:\Dev\Test\node_modules\ref\src\binding.cc(586): error C2661: 'v8::Object::Set': no overloaded function takes 2 arguments [C:\Dev\Test\node_modules\ref\build\binding.vcxproj]
C:\Dev\Test\node_modules\ref\src\binding.cc(587): error C2661: 'v8::Object::Set': no overloaded function takes 2 arguments [C:\Dev\Test\node_modules\ref\build\binding.vcxproj]
C:\Dev\Test\node_modules\ref\src\binding.cc(588): error C2661: 'v8::Object::Set': no overloaded function takes 2 arguments [C:\Dev\Test\node_modules\ref\build\binding.vcxproj]
C:\Dev\Test\node_modules\ref\src\binding.cc(589): error C2661: 'v8::Object::Set': no overloaded function takes 2 arguments [C:\Dev\Test\node_modules\ref\build\binding.vcxproj]
C:\Dev\Test\node_modules\ref\src\binding.cc(590): error C2661: 'v8::Object::Set': no overloaded function takes 2 arguments [C:\Dev\Test\node_modules\ref\build\binding.vcxproj]
C:\Dev\Test\node_modules\ref\src\binding.cc(591): error C2661: 'v8::Object::Set': no overloaded function takes 2 arguments [C:\Dev\Test\node_modules\ref\build\binding.vcxproj]

**Comment by jimfilippou** [comment]
This seems to be a node-gyp issue, check these solutions yth52G7NWuiXcnk7UnZfpI6xotPk8EfF5riT7umw7aqnn

**Comment by jimfilippou** [comment]
It seems that this issue is caused by node-gyp and it is happening in a lower level. If you fix your node-gyp installation or refresh it, I think it will work. Check these solutions out https://github.com/nodejs/node-gyp/issues/809 and let me know what happens. 

Best of luck!

**Comment by p-g-krish** [comment]
> It seems that this issue is caused by node-gyp and it is happening in a lower level. If you fix your node-gyp installation or refresh it, I think it will work. Check these solutions out [nodejs/node-gyp#809](https://github.com/nodejs/node-gyp/issues/809) and let me know what happens.
> 
> Best of luck!

It's working. Issue resolved

**Comment by jimfilippou** [comment]
That's great news! happy hacking
